sudo: false

language: scala

scala:
   - 2.11.11
   - 2.12.4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/google-cloud-sdk

env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin

before_install:
  - openssl aes-256-cbc -K $encrypted_c3e85ceadb2f_key -iv $encrypted_c3e85ceadb2f_iv -in gcloud-account.json.enc -out gcloud-account.json -d
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
       echo "here1";
       curl https://sdk.cloud.google.com | bash;
       gcloud -q components install pubsub-emulator;
       echo "here2";
    else
      echo "else!!!";
    fi
  - gcloud auth activate-service-account --key-file gcloud-account.json

install:
  - gcloud -q components update

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
